server:
    port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver     This is deprecated
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
  mail:
    host: smtp.qq.com
    username: 1559843332@qq.com # 用户名
    password: 授权码 # 不是密码，是授权码
    properties: {mail.smtp.auth=true,mail.smtp.starttls.enable=true,mail.smtp.starttls.required=true}

  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    password: 123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100s
    # 连接超时时间（毫秒）
    timeout: 5s
    #默认是索引为0的数据库
    database: 0

mybatis:
  typeAliasesPackage: com.ocean.entity
  mapperLocations: classpath:mapping/*.xml



logging:
  config: classpath:logback.xml


