server:
    port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver     This is deprecated
    url: jdbc:mysql://39.105.97.50:3306/github?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
  mail:
    host: smtp.qq.com
    username: 1559843332@qq.com # 用户名
    password: 授权码 # 不是密码，是授权码
    properties: {mail.smtp.auth=true,mail.smtp.starttls.enable=true,mail.smtp.starttls.required=true}


mybatis:
  typeAliasesPackage: com.ocean.entity
  mapperLocations: classpath:mapping/*.xml



logging:
  config: classpath:logback.xml


