server:
    port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver     This is deprecated
    url: null
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/


mybatis:
  typeAliasesPackage: com.ocean.entity
  mapperLocations: classpath:mapping/*.xml



logging:
  config: classpath:logback.xml
